server:
  port: 8080

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: https://discovery-server.apps.sys.tas.tkgi.haas-451.pez.vmware.com
