spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
---
spring:
  profiles: cloud
  zipkin:
    baseUrl: https://tracing-server.apps.sys.tas.tkgi.haas-451.pez.vmware.com
server:
  port: 8080
eureka:
  #workaround, what about multiple instances?
  instance:
    hostname: customer-service.apps.sys.tas.tkgi.haas-451.pez.vmware.com:443
  client:
    serviceUrl:
      defaultZone: https://discovery-server.apps.sys.tas.tkgi.haas-451.pez.vmware.com/eureka/
